### ISSUE TITLE
Stale secret deletion

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/dvc-oss#27]
It looks like the following GitHub Actions secrets aren't being used in any of your workflows, at least on the default branch:
* OSS_ACCESS_KEY_ID
* OSS_ACCESS_KEY_SECRET
* OSS_ENDPOINT

Please ping @iterative/security before 2023-09-22 if you'd like to preserve them.

**Comment by 0x2b3bfa0** [comment]
`--assume-yes`

**Comment by efiop** [comment]
Looks like this is a new test failure reason https://github.com/iterative/dvc-oss/issues/28

No worries, will add new ones.
