### ISSUE TITLE
Error when uploading large file!

### ISSUE THREAD

**Issue by zijunsun** [iterative/dvc-oss#4]
I use this tool to upload file to oss.
13 of 15  upload successful.
2 of 15 return error message:
`ERROR: failed to transfer 'md5: 91696faeb5546c1cfdd9dcb3b0979d78' - {'status': 403, 'x-oss-request-id': '6315D9E34050BF35345889CF', 'details': {'Code': 'AccessDenied', 'Message': 'You have no right to access this object.', 'RequestId': '6315D9E34050BF35345889CF', 'HostId': 'ailab-online.oss-cn-beijing.aliyuncs.com'}}`
I found that these two files are large file, more than 400M.
Is there any limit when uploading large file?

**Comment by zijunsun** [comment]
I tested that file larger than 100M can not upload to oss.
And while reading the source code, I found this line:
https://github.com/iterative/dvc-oss/blob/fb81c509134c05b2c801f1116dce0181791188e4/dvc_oss/__init__.py#L16
I am not sure whether it is the limitation of the file size.

**Comment by zijunsun** [comment]
![image](https://user-images.githubusercontent.com/20966464/188594062-58a272ba-57fb-4bf6-9f98-97761b1ad8f9.png)

**Comment by rlamy** [comment]
@zijunsun The actual line that triggers the failure is:
https://github.com/fsspec/ossfs/blob/07dcbd35e67221d178e16948f568c83b5b38830e/ossfs/core.py#L630

If you lookup the value, you'll find that it is 104857600.

**Comment by karajan1001** [comment]
```
ERROR: failed to transfer 'md5: 91696faeb5546c1cfdd9dcb3b0979d78' - {'status': 403, 'x-oss-request-id': '6315D9E34050BF35345889CF', 'details': {'Code': 'AccessDenied', 'Message': 'You have no right to access this object.', 'RequestId': '6315D9E34050BF35345889CF', 'HostId': 'ailab-online.oss-cn-beijing.aliyuncs.com'}}
```

I tried on `ossfs` to a data larger than this threshold but didn't got the permission error. 
1. What is the permission setting of your bucket. 
2. Could you please provide some more detailed log via `-vv` flag after the command.

**Comment by karajan1001** [comment]
Close as conversation

```
sunzijun — 09/16/2022
It seems ok for me now. I think I did not change anything. It's just goes well.
Gao — 09/16/2022
Quite weird maybe something ﻿goes wrong on the OSS side. Thanks for your report anyway.
sunzijun — 09/16/2022
Thanks for your support! You can close the issue.
```
